"""Generated-Triton execution backend for NeuralStateSpace: persistent GPU rollout and BPTT.

The rollout runs as ONE persistent kernel: all L steps in a single launch, weights resident
on-chip, one program per trajectory. Each layer is computed as a broadcast-reduce GEMV
(``tl.sum(z[:, :, None] * W[None, :, :], axis=1)``, plain FMA) instead of ``tl.dot`` — this
removes the tensor-core M>=16 tile minimum so a single trajectory per program is possible,
which is what makes small-batch rollouts fill the GPU. fp32-exact (no TF32 in the recurrence).

Backward follows the split-BPTT design: the training forward additionally stores the hidden
activations; a persistent reverse-sweep kernel carries the state adjoint and emits the
per-step pre-activation adjoints; the parameter gradients are batched cuBLAS GEMMs over the
``[B*L, .]`` flattened adjoints (``mlp_param_grads``).

Kernels are generated from the layer spec (dims baked as literals) into a cached module file,
so arbitrary MLP depths/widths are supported up to the on-chip limit (padded widths <= 128).
"""

__all__ = [
    "triton_rollout",
    "is_available",
    "fits",
]

import hashlib
import importlib.util
import os
from pathlib import Path

import torch

from .core import SSMSpec, check_rollout_args, mlp_param_grads

_ACT_TL = {
    "tanh": ("2.0 * tl.sigmoid(2.0 * ({a})) - 1.0", "(1.0 - {z} * {z})"),
    "sigmoid": ("tl.sigmoid({a})", "({z} * (1.0 - {z}))"),
    "relu": ("tl.maximum({a}, 0.0)", "tl.where({z} > 0.0, 1.0, 0.0)"),
}

_MAX_PADDED_WIDTH = 128

_KERNELS: dict[SSMSpec, object] = {}


def is_available() -> bool:
    if not torch.cuda.is_available():
        return False
    try:
        import triton  # noqa: F401
    except ImportError:
        return False
    return True


def _pow2(n: int) -> int:
    return 1 << (n - 1).bit_length()


def fits(spec: SSMSpec) -> bool:
    """Whether the persistent GEMV kernels apply: all padded widths must stay on-chip."""
    return spec.act in _ACT_TL and max(_pow2(d) for d in (*spec.dims, spec.n_input)) <= _MAX_PADDED_WIDTH


def _gen_source(spec: SSMSpec) -> str:
    """Emit the spec-specialized Triton kernel module (inference fwd, training fwd, bwd)."""
    nx, nu, k = spec.n_state, spec.n_input, spec.n_linear
    px, pu = _pow2(nx), _pow2(nu)
    ph = [_pow2(h) for h in spec.hidden]  # padded hidden widths
    pdims = (px, *ph, px)  # padded layer io sizes (input x-part handled separately)
    act, dact = _ACT_TL[spec.act]

    ranges = sorted({px, pu, *ph})
    lines = [
        '"""Auto-generated by tsfast.models.ssm.backend_triton — do not edit."""',
        "import triton",
        "import triton.language as tl",
        "",
    ]

    def emit_ranges(out: list[str]):
        for n in ranges:
            out.append(f"    r{n} = tl.arange(0, {n})")

    def emit_weight_loads(out: list[str], with_biases: bool):
        out.append(f"    w0x = tl.load(w0x_ptr + r{px}[:, None] * {pdims[1]} + r{pdims[1]}[None, :])")
        if with_biases:  # only the forward kernels take w0u (the backward never uses it)
            out.append(f"    w0u = tl.load(w0u_ptr + r{pu}[:, None] * {pdims[1]} + r{pdims[1]}[None, :])")
        if with_biases:
            out.append(f"    c0 = tl.load(c0_ptr + r{pdims[1]})")
        for i in range(1, k):
            out.append(
                f"    w{i} = tl.load(w{i}_ptr + r{pdims[i]}[:, None] * {pdims[i + 1]} + r{pdims[i + 1]}[None, :])"
            )
            if with_biases:
                out.append(f"    c{i} = tl.load(c{i}_ptr + r{pdims[i + 1]})")

    def fwd_kernel(name: str, store_z: bool) -> list[str]:
        w_args = "w0x_ptr, w0u_ptr, c0_ptr" + "".join(f", w{i}_ptr, c{i}_ptr" for i in range(1, k))
        z_args = "".join(f"z{i}_ptr, " for i in range(k - 1)) if store_z else ""
        out = [
            "@triton.jit",
            f"def {name}(u_ptr, x0_ptr, {w_args}, out_ptr, {z_args}B, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
        ]
        emit_ranges(out)
        emit_weight_loads(out, with_biases=True)
        xmask = f", mask=(r{px}[None, :] < {nx}), other=0.0" if px != nx else ""
        out.append(f"    x = tl.load(x0_ptr + pid * {nx} + r{px}[None, :]{xmask})")
        out.append("    for t in tl.range(0, L, num_stages=NUM_STAGES):")
        umask = f", mask=(r{pu}[None, :] < {nu}), other=0.0" if pu != nu else ""
        out.append(f"        uu = tl.load(u_ptr + pid * (L * {nu}) + t * {nu} + r{pu}[None, :]{umask})")
        prev = None
        for i in range(k):
            dst = "x" if i == k - 1 else f"z{i}"
            if i == 0:
                expr = (
                    "tl.sum(x[:, :, None] * w0x[None, :, :], axis=1)"
                    " + tl.sum(uu[:, :, None] * w0u[None, :, :], axis=1) + c0[None, :]"
                )
            else:
                expr = f"tl.sum({prev}[:, :, None] * w{i}[None, :, :], axis=1) + c{i}[None, :]"
            if i < k - 1:
                out.append(f"        {dst} = " + act.format(a=expr))
                if store_z:
                    h, p = spec.hidden[i], ph[i]
                    zmask = f", mask=(r{p}[None, :] < {h})" if p != h else ""
                    out.append(f"        tl.store(z{i}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :], {dst}{zmask})")
            else:
                out.append(f"        {dst} = {expr}")
            prev = dst
        omask = f", mask=(r{px}[None, :] < {nx})" if px != nx else ""
        out.append(f"        tl.store(out_ptr + pid * (L * {nx}) + t * {nx} + r{px}[None, :], x{omask})")
        out.append("")
        return out

    def bwd_kernel() -> list[str]:
        z_args = "".join(f"z{i}_ptr, " for i in range(k - 1))
        w_args = "w0x_ptr" + "".join(f", w{i}_ptr" for i in range(1, k))
        ga_args = "".join(f"ga{i}_ptr, " for i in range(k - 1))
        out = [
            "@triton.jit",
            f"def ssm_bwd(gout_ptr, {z_args}{w_args}, gy_ptr, {ga_args}gx0_ptr, B, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
        ]
        emit_ranges(out)
        emit_weight_loads(out, with_biases=False)
        out.append(f"    carry = tl.zeros([1, {px}], dtype=tl.float32)")
        out.append("    for ti in tl.range(0, L, num_stages=NUM_STAGES):")
        out.append("        t = L - 1 - ti")
        gmask = f", mask=(r{px}[None, :] < {nx}), other=0.0" if px != nx else ""
        smask = f", mask=(r{px}[None, :] < {nx})" if px != nx else ""
        out.append(f"        gout = tl.load(gout_ptr + pid * (L * {nx}) + t * {nx} + r{px}[None, :]{gmask})")
        out.append("        gy = gout + carry")
        out.append(f"        tl.store(gy_ptr + pid * (L * {nx}) + t * {nx} + r{px}[None, :], gy{smask})")
        prev = "gy"
        for i in range(k - 1, 0, -1):
            h, p = spec.hidden[i - 1], ph[i - 1]
            zmask = f", mask=(r{p}[None, :] < {h}), other=0.0" if p != h else ""
            zsmask = f", mask=(r{p}[None, :] < {h})" if p != h else ""
            out.append(f"        zv{i - 1} = tl.load(z{i - 1}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :]{zmask})")
            out.append(f"        gh{i - 1} = tl.sum({prev}[:, None, :] * w{i}[None, :, :], axis=2)")
            out.append(f"        ga{i - 1} = gh{i - 1} * " + dact.format(z=f"zv{i - 1}"))
            out.append(
                f"        tl.store(ga{i - 1}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :], ga{i - 1}{zsmask})"
            )
            prev = f"ga{i - 1}"
        out.append(f"        carry = tl.sum({prev}[:, None, :] * w0x[None, :, :], axis=2)")
        gx0mask = f", mask=(r{px}[None, :] < {nx})" if px != nx else ""
        out.append(f"    tl.store(gx0_ptr + pid * {nx} + r{px}[None, :], carry{gx0mask})")
        out.append("")
        return out

    lines += fwd_kernel("ssm_fwd", store_z=False)
    lines += fwd_kernel("ssm_fwd_train", store_z=True)
    lines += bwd_kernel()
    return "\n".join(lines)


def _get_kernels(spec: SSMSpec):
    """Generate, cache on disk, and import the kernel module for this spec."""
    mod = _KERNELS.get(spec)
    if mod is None:
        src = _gen_source(spec)
        tag = hashlib.md5(src.encode()).hexdigest()[:10]
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser() / "tsfast" / "ssm_triton"
        cache_dir.mkdir(parents=True, exist_ok=True)
        path = cache_dir / f"ssm_{tag}.py"
        if not path.exists() or path.read_text() != src:
            path.write_text(src)
        spec_ = importlib.util.spec_from_file_location(f"tsfast_ssm_triton_{tag}", path)
        mod = importlib.util.module_from_spec(spec_)
        spec_.loader.exec_module(mod)
        _KERNELS[spec] = mod
    return mod


def _num_warps(spec: SSMSpec) -> int:
    # findings from the GEMV kernels: nw=2 up to width 64, nw=8 at 128 (nw=4 spills)
    return 2 if max(_pow2(d) for d in spec.dims) <= 64 else 8


@torch.no_grad()
def _prep_weights(spec: SSMSpec, weights: list[torch.Tensor], biases: list[torch.Tensor] | None) -> list[torch.Tensor]:
    """Pad/transpose the raw nn.Linear parameters into the kernel layout.

    Returns ``[w0x, w0u, c0, w1, c1, ...]`` (biases interleaved) when biases are given —
    the forward-kernel argument order — or just the weight buffers for the backward kernel.
    """
    nx, k = spec.n_state, spec.n_linear
    px, pu = _pow2(nx), _pow2(spec.n_input)
    ph = [_pow2(h) for h in spec.hidden]
    pdims = (px, *ph, px)
    dev = weights[0].device
    w0 = weights[0]
    w0x = torch.zeros(px, pdims[1], device=dev)
    w0x[:nx, : w0.shape[0]] = w0[:, :nx].t()
    w0u = torch.zeros(pu, pdims[1], device=dev)
    w0u[: spec.n_input, : w0.shape[0]] = w0[:, nx:].t()
    bufs = [w0x, w0u]
    if biases is not None:
        c0p = torch.zeros(pdims[1], device=dev)
        c0p[: biases[0].shape[0]] = biases[0]
        bufs.append(c0p)
    for i in range(1, k):
        w = weights[i]
        wp = torch.zeros(pdims[i], pdims[i + 1], device=dev)
        wp[: w.shape[1], : w.shape[0]] = w.t()
        bufs.append(wp)
        if biases is not None:
            cp = torch.zeros(pdims[i + 1], device=dev)
            cp[: biases[i].shape[0]] = biases[i]
            bufs.append(cp)
    return [b.contiguous() for b in bufs]


def _run_fwd(mod, spec: SSMSpec, u, x0, params, store_z, num_warps):
    B, L = u.shape[0], u.shape[1]
    dev = u.device
    out = torch.empty(B, L, spec.n_state, device=dev, dtype=torch.float32)
    bufs = _prep_weights(spec, [w.detach() for w in params[0::2]], [c.detach() for c in params[1::2]])
    if store_z:
        zs = [torch.empty(B, L, h, device=dev, dtype=torch.float32) for h in spec.hidden]
        mod.ssm_fwd_train[(B,)](u, x0, *bufs, out, *zs, B, L, NUM_STAGES=3, num_warps=num_warps)
    else:
        zs = []
        mod.ssm_fwd[(B,)](u, x0, *bufs, out, B, L, NUM_STAGES=3, num_warps=num_warps)
    return out, zs


class _TritonSSMRollout(torch.autograd.Function):
    @staticmethod
    def forward(ctx, mod, spec, u, x0, *params):
        u = u.contiguous()
        x0 = x0.contiguous()
        nw = _num_warps(spec)
        out, zs = _run_fwd(mod, spec, u, x0, params, store_z=True, num_warps=nw)
        ctx.mod, ctx.spec, ctx.nw = mod, spec, nw
        ctx.save_for_backward(u, x0, out, *zs, *params[0::2])
        return out

    @staticmethod
    def backward(ctx, grad_out):
        mod, spec = ctx.mod, ctx.spec
        k = spec.n_linear
        saved = ctx.saved_tensors
        u, x0, out = saved[0], saved[1], saved[2]
        zs = list(saved[3 : 3 + k - 1])
        weights = list(saved[3 + k - 1 :])
        B, L = u.shape[0], u.shape[1]
        dev = u.device
        bufs = _prep_weights(spec, [w.detach() for w in weights], biases=None)
        wk = [bufs[0]] + bufs[2:]  # w0x, w1, ..., w{k-1} (w0u unused by the backward)
        gy = torch.empty(B, L, spec.n_state, device=dev, dtype=torch.float32)
        gas = [torch.empty_like(z) for z in zs]
        gx0 = torch.empty(B, spec.n_state, device=dev, dtype=torch.float32)
        mod.ssm_bwd[(B,)](grad_out.contiguous(), *zs, *wk, gy, *gas, gx0, B, L, NUM_STAGES=3, num_warps=ctx.nw)
        grads, du = mlp_param_grads(spec, x0, u, out, zs, gy, gas, w0=weights[0], need_du=ctx.needs_input_grad[2])
        dx0 = gx0 if ctx.needs_input_grad[3] else None
        return (None, None, du, dx0, *grads)


def triton_rollout(spec: SSMSpec, u: torch.Tensor, x0: torch.Tensor, params: list[torch.Tensor]) -> torch.Tensor:
    """Run the rollout through the generated persistent Triton kernels (autograd-capable)."""
    check_rollout_args(spec, u, x0, "cuda")
    if not fits(spec):
        raise RuntimeError(
            f"spec {spec} exceeds the triton backend envelope (padded widths <= {_MAX_PADDED_WIDTH}); "
            "use backend='compiled'"
        )
    mod = _get_kernels(spec)
    if not torch.is_grad_enabled() or not any(t.requires_grad for t in [u, x0, *params]):
        out, _ = _run_fwd(mod, spec, u.contiguous(), x0.contiguous(), params, store_z=False, num_warps=_num_warps(spec))
        return out
    return _TritonSSMRollout.apply(mod, spec, u, x0, *params)
