"""Generated-Triton execution backend for the REN rollout: persistent GPU rollout and BPTT.

The rollout runs as ONE persistent kernel: all ``L`` steps in a single launch, the explicit
realization resident on-chip, one program per trajectory. Every matrix product is a
broadcast-reduce GEMV (``tl.sum(x[:, None] * W, axis=0)``, plain FMA) rather than
``tl.dot`` — this removes the tensor-core ``M>=16`` tile minimum, so a single trajectory per
program is possible and small-batch rollouts still fill the GPU. fp32-exact (no TF32).

The equilibrium sweep stays in registers. It is a static loop over the ``n_nl`` neurons:
neuron ``i`` reads its own pre-activation out of the accumulator by a masked reduction,
applies the activation, and rank-1-updates the accumulator with column ``i`` of ``D11`` —
one contiguous vector load from the transposed copy. The reverse sweep in the backward is
the mirror image, and needs no triangular masking at all: ``D11`` is strictly lower
triangular, so the full dot with column ``i`` already excludes every neuron ``k <= i``.

Backward follows the split-BPTT design of ``MATH_REN.md``: the training forward stores the
per-step states and equilibrium activations; a persistent reverse kernel carries the state
adjoint and emits the two per-step adjoint sequences; the parameter gradients are batched
cuBLAS GEMMs over the ``[B*L, .]`` flattened adjoints (``ren_param_grads``, applied inside
the ``tsfast::ren_rollout_bwd`` op). Inputs arrive from the ``tsfast::ren_rollout*`` custom
ops as contiguous float32 CUDA tensors.

Kernels are generated from the spec (dims baked as literals) into a cached module file.
"""

__all__ = [
    "supports",
    "fits",
    "forward_infer",
    "forward_train",
    "backward",
    "is_available",
]

import hashlib
import importlib.util
import os
from pathlib import Path

import torch

from ..._core.kernel_triton import _ACT_TL, _pow2, is_available
from .common import RENSpec
from .core import rollout_unsupported

_KERNELS: dict[RENSpec, object] = {}

#: On-chip caps. The state/neuron product bounds the largest register tile (``C1``, ``B1``);
#: the rest are the per-vector padded widths.
MAX_PX = 64
MAX_PV = 128
MAX_PU = 64
MAX_PY = 64
MAX_PX_PV = 4096


def _pads(spec: RENSpec) -> tuple[int, int, int, int]:
    return _pow2(spec.n_state), _pow2(spec.n_nl), _pow2(spec.n_input), _pow2(spec.n_output)


def fits(spec: RENSpec) -> bool:
    """Whether the persistent kernels apply: every padded tile must stay on-chip."""
    px, pv, pu, py = _pads(spec)
    return (
        spec.act in _ACT_TL and px <= MAX_PX and pv <= MAX_PV and pu <= MAX_PU and py <= MAX_PY and px * pv <= MAX_PX_PV
    )


def _gen_source(spec: RENSpec) -> str:
    """Emit the spec-specialized Triton kernel module (inference fwd, training fwd, bwd)."""
    nx, nv, nu, ny = spec.n_state, spec.n_nl, spec.n_input, spec.n_output
    px, pv, pu, py = _pads(spec)
    act, dact = _ACT_TL[spec.act]
    lines = [
        '"""Auto-generated by tsfast.models.architectures.ren.backend_triton — do not edit."""',
        "import triton",
        "import triton.language as tl",
        "",
    ]

    def ranges(names: str) -> list[str]:
        sizes = {"x": px, "v": pv, "u": pu, "y": py}
        return [f"    r{n} = tl.arange(0, {sizes[n]})" for n in names]

    def tile(name: str, rows: int, cols: int, rr: str, rc: str) -> str:
        return f"    {name} = tl.load({name}_ptr + r{rr}[:, None] * {cols} + r{rc}[None, :])"

    # ------------------------------------------------------------------- forward
    fwd_args = (
        "u_ptr, x0_ptr, at_ptr, b1t_ptr, b2t_ptr, c1t_ptr, d11c_ptr, d12t_ptr, "
        "c2t_ptr, d21t_ptr, d22t_ptr, bx_ptr, bv_ptr, by_ptr, y_ptr, xlast_ptr"
    )

    def fwd_kernel(name: str, store: bool) -> list[str]:
        extra = ", xs_ptr, ws_ptr" if store else ""
        out = [
            "@triton.jit",
            f"def {name}({fwd_args}{extra}, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
            *ranges("xvuy"),
            tile("at", px, px, "x", "x"),
            tile("b1t", pv, px, "v", "x"),
            tile("b2t", pu, px, "u", "x"),
            tile("c1t", px, pv, "x", "v"),
            tile("d12t", pu, pv, "u", "v"),
            tile("c2t", px, py, "x", "y"),
            tile("d21t", pv, py, "v", "y"),
            tile("d22t", pu, py, "u", "y"),
            "    bx = tl.load(bx_ptr + rx)",
            "    bv = tl.load(bv_ptr + rv)",
            "    by = tl.load(by_ptr + ry)",
            f"    x = tl.load(x0_ptr + pid * {nx} + rx, mask=rx < {nx}, other=0.0)",
            "    for t in tl.range(0, L, num_stages=NUM_STAGES):",
            "        base = pid * L + t",
            f"        ut = tl.load(u_ptr + base * {nu} + ru, mask=ru < {nu}, other=0.0)",
            "        acc = bv + tl.sum(x[:, None] * c1t, axis=0) + tl.sum(ut[:, None] * d12t, axis=0)",
            f"        w = tl.zeros([{pv}], tl.float32)",
        ]
        for i in range(nv):
            out.append(f"        a{i} = tl.sum(tl.where(rv == {i}, acc, 0.0))")
            out.append(f"        w{i} = " + act.format(a=f"a{i}"))
            out.append(f"        w = tl.where(rv == {i}, w{i}, w)")
            if i + 1 < nv:
                # column i of D11, read as row i of the transposed copy: one contiguous load
                out.append(f"        acc = acc + w{i} * tl.load(d11c_ptr + {i * pv} + rv)")
        out += [
            "        yv = by + tl.sum(x[:, None] * c2t, axis=0) + tl.sum(w[:, None] * d21t, axis=0)"
            " + tl.sum(ut[:, None] * d22t, axis=0)",
            f"        tl.store(y_ptr + base * {ny} + ry, yv, mask=ry < {ny})",
        ]
        if store:
            out += [
                f"        tl.store(xs_ptr + base * {nx} + rx, x, mask=rx < {nx})",
                f"        tl.store(ws_ptr + base * {nv} + rv, w, mask=rv < {nv})",
            ]
        out += [
            "        x = bx + tl.sum(x[:, None] * at, axis=0) + tl.sum(w[:, None] * b1t, axis=0)"
            " + tl.sum(ut[:, None] * b2t, axis=0)",
            f"    tl.store(xlast_ptr + pid * {nx} + rx, x, mask=rx < {nx})",
            "",
        ]
        return out

    lines += fwd_kernel("ren_fwd", store=False)
    lines += fwd_kernel("ren_fwd_train", store=True)

    # ------------------------------------------------------------------ backward
    lines += [
        "@triton.jit",
        "def ren_bwd(gy_ptr, gxl_ptr, ws_ptr, a_ptr, b1_ptr, c1_ptr, c2_ptr, d21_ptr, d11c_ptr, "
        "lam_ptr, gv_ptr, gx0_ptr, L, NUM_STAGES: tl.constexpr):",
        "    pid = tl.program_id(0)",
        *ranges("xvy"),
        tile("a", px, px, "x", "x"),
        tile("b1", px, pv, "x", "v"),
        tile("c1", pv, px, "v", "x"),
        tile("c2", py, px, "y", "x"),
        tile("d21", py, pv, "y", "v"),
        f"    carry = tl.load(gxl_ptr + pid * {nx} + rx, mask=rx < {nx}, other=0.0)",
        "    for t in tl.range(L - 1, -1, -1, num_stages=NUM_STAGES):",
        "        base = pid * L + t",
        f"        gyt = tl.load(gy_ptr + base * {ny} + ry, mask=ry < {ny}, other=0.0)",
        f"        wt = tl.load(ws_ptr + base * {nv} + rv, mask=rv < {nv}, other=0.0)",
        "        gwd = tl.sum(gyt[:, None] * d21, axis=0) + tl.sum(carry[:, None] * b1, axis=0)",
        f"        gv = tl.zeros([{pv}], tl.float32)",
    ]
    for i in range(nv - 1, -1, -1):
        # the dot with column i needs no k > i mask: D11 is strictly lower triangular, so
        # every entry at or above the diagonal is already zero
        col = f"tl.sum(tl.load(d11c_ptr + {i * pv} + rv) * gv)" if i + 1 < nv else "0.0"
        lines.append(f"        s{i} = tl.sum(tl.where(rv == {i}, gwd, 0.0)) + {col}")
        lines.append(f"        z{i} = tl.sum(tl.where(rv == {i}, wt, 0.0))")
        lines.append(f"        gv = tl.where(rv == {i}, s{i} * " + dact.format(z=f"z{i}") + ", gv)")
    lines += [
        f"        tl.store(lam_ptr + base * {nx} + rx, carry, mask=rx < {nx})",
        f"        tl.store(gv_ptr + base * {nv} + rv, gv, mask=rv < {nv})",
        "        carry = tl.sum(carry[:, None] * a, axis=0) + tl.sum(gyt[:, None] * c2, axis=0)"
        " + tl.sum(gv[:, None] * c1, axis=0)",
        f"    tl.store(gx0_ptr + pid * {nx} + rx, carry, mask=rx < {nx})",
        "",
    ]
    return "\n".join(lines)


def _get_kernels(spec: RENSpec):
    """Generate, cache on disk, and import the kernel module for this spec."""
    mod = _KERNELS.get(spec)
    if mod is None:
        src = _gen_source(spec)
        tag = hashlib.md5(src.encode(), usedforsecurity=False).hexdigest()[:10]
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser() / "tsfast" / "ren_triton"
        cache_dir.mkdir(parents=True, exist_ok=True)
        path = cache_dir / f"ren_{tag}.py"
        if not path.exists() or path.read_text() != src:
            path.write_text(src)
        loader = importlib.util.spec_from_file_location(f"tsfast_ren_triton_{tag}", path)
        mod = importlib.util.module_from_spec(loader)
        loader.loader.exec_module(mod)
        _KERNELS[spec] = mod
    return mod


def _num_warps(spec: RENSpec) -> int:
    return 2 if max(_pads(spec)) <= 64 else 8


@torch.no_grad()
def _pad(t: torch.Tensor, rows: int, cols: int, transpose: bool) -> torch.Tensor:
    src = t.t() if transpose else t
    out = torch.zeros(rows, cols, device=t.device, dtype=torch.float32)
    out[: src.shape[0], : src.shape[1]] = src
    return out


@torch.no_grad()
def _pad_vec(t: torch.Tensor, n: int) -> torch.Tensor:
    out = torch.zeros(n, device=t.device, dtype=torch.float32)
    out[: t.shape[0]] = t
    return out


@torch.no_grad()
def _fwd_bufs(spec: RENSpec, params: list[torch.Tensor]) -> list[torch.Tensor]:
    """Transposed, zero-padded tiles in the forward kernel's argument order."""
    px, pv, pu, py = _pads(spec)
    a, b1, b2, c1, d11, d12, c2, d21, d22, bx, bv, by = (p.detach() for p in params)
    return [
        _pad(a, px, px, True),
        _pad(b1, pv, px, True),
        _pad(b2, pu, px, True),
        _pad(c1, px, pv, True),
        _pad(d11, pv, pv, True),
        _pad(d12, pu, pv, True),
        _pad(c2, px, py, True),
        _pad(d21, pv, py, True),
        _pad(d22, pu, py, True),
        _pad_vec(bx, px),
        _pad_vec(bv, pv),
        _pad_vec(by, py),
    ]


@torch.no_grad()
def _bwd_bufs(spec: RENSpec, params: list[torch.Tensor]) -> list[torch.Tensor]:
    """Untransposed, zero-padded tiles in the backward kernel's argument order.

    The adjoint sums run over the *output* index of each map, so the backward reads the
    matrices the way they are stored; only ``D11`` keeps the transposed copy, which serves
    both directions since both need its columns.
    """
    px, pv, pu, py = _pads(spec)
    a, b1, _, c1, d11, _, c2, d21 = (params[i].detach() for i in (0, 1, 2, 3, 4, 5, 6, 7))
    return [
        _pad(a, px, px, False),
        _pad(b1, px, pv, False),
        _pad(c1, pv, px, False),
        _pad(c2, py, px, False),
        _pad(d21, py, pv, False),
        _pad(d11, pv, pv, True),
    ]


def supports(spec: RENSpec, u: torch.Tensor, x0: torch.Tensor) -> str | None:
    """Reason the persistent Triton kernels cannot handle these inputs, or None when they can."""
    reason = rollout_unsupported(spec, u, x0, "cuda", (torch.float32,))
    if reason is not None:
        return reason
    if not is_available():
        return "no CUDA / triton"
    if not fits(spec):
        return (
            f"spec exceeds the on-chip caps (padded n_state<={MAX_PX}, n_nl<={MAX_PV}, "
            f"n_input<={MAX_PU}, n_output<={MAX_PY}, n_state*n_nl<={MAX_PX_PV})"
        )
    return None


def _run_fwd(spec: RENSpec, u, x0, params, store: bool):
    mod = _get_kernels(spec)
    b, ln = u.shape[0], u.shape[1]
    dev = u.device
    y = torch.empty(b, ln, spec.n_output, device=dev, dtype=torch.float32)
    xlast = torch.empty(b, spec.n_state, device=dev, dtype=torch.float32)
    bufs = _fwd_bufs(spec, params)
    warps = _num_warps(spec)
    if store:
        xs = torch.empty(b, ln, spec.n_state, device=dev, dtype=torch.float32)
        ws = torch.empty(b, ln, spec.n_nl, device=dev, dtype=torch.float32)
        mod.ren_fwd_train[(b,)](u, x0, *bufs, y, xlast, xs, ws, ln, NUM_STAGES=2, num_warps=warps)
        return y, xlast, xs, ws
    mod.ren_fwd[(b,)](u, x0, *bufs, y, xlast, ln, NUM_STAGES=2, num_warps=warps)
    return y, xlast, None, None


def forward_infer(spec: RENSpec, u, x0, params) -> tuple[torch.Tensor, torch.Tensor]:
    """Rollout without stored intermediates: returns ``(y, x_L)``."""
    y, xlast, _, _ = _run_fwd(spec, u, x0, params, store=False)
    return y, xlast


def forward_train(spec: RENSpec, u, x0, params) -> tuple[torch.Tensor, ...]:
    """Rollout that also stores the BPTT tape: returns ``(y, x_L, xs, ws)``."""
    return _run_fwd(spec, u, x0, params, store=True)


def backward(spec: RENSpec, gy, gxl, xs, ws, params) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
    """Sequential adjoint recurrence: returns ``(lam, gv, gx0)`` for the shared GEMM stage."""
    mod = _get_kernels(spec)
    b, ln = gy.shape[0], gy.shape[1]
    dev = gy.device
    lam = torch.empty(b, ln, spec.n_state, device=dev, dtype=torch.float32)
    gv = torch.empty(b, ln, spec.n_nl, device=dev, dtype=torch.float32)
    gx0 = torch.empty(b, spec.n_state, device=dev, dtype=torch.float32)
    mod.ren_bwd[(b,)](gy, gxl, ws, *_bwd_bufs(spec, params), lam, gv, gx0, ln, NUM_STAGES=2, num_warps=_num_warps(spec))
    return lam, gv, gx0
