"""Generated-Triton execution backend for the R2DN rollout: persistent GPU rollout and BPTT.

The rollout runs as ONE persistent kernel: all ``L`` steps in a single launch, the explicit
realization and the whole 1-Lipschitz network resident on-chip, one program per trajectory.
Every matrix product is a broadcast-reduce GEMV (``tl.sum(x[:, None] * W, axis=0)``, plain
FMA) rather than ``tl.dot`` — this removes the tensor-core ``M>=16`` tile minimum, so a
single trajectory per program is possible and small-batch rollouts still fill the GPU.
fp32-exact (no TF32).

Dropping the REN's equilibrium sweep is what makes the R2DN cheap *per step*, but it does
nothing about the launches: an eager rollout still issues ``L * (8 + 3*depth)`` tiny kernels
and is dispatch-bound exactly as the REN's is. This backend removes them, which is worth far
more than the sweep ever cost — the network's layers are collapsed into the same launch as
the recurrence, so cost becomes flat in depth as well as in sequence length.

Backward follows the split-BPTT design of ``MATH_R2DN.md``: the training forward stores the
per-step states, network inputs/outputs and per-layer activations; a persistent reverse
kernel carries the state adjoint through the network's backward — which cannot be lifted out
of the sequential loop, since ``gv_t`` depends on ``λ_{t+1}`` — and emits the per-step adjoint
sequences; the parameter gradients are batched cuBLAS GEMMs over the ``[B*L, .]`` flattened
adjoints (``r2dn_param_grads``, applied inside the ``tsfast::r2dn_rollout_bwd`` op). Inputs
arrive from the ``tsfast::r2dn_rollout*`` custom ops as contiguous float32 CUDA tensors, with
``Ψ`` and ``√2`` already folded into the layer weights.

Kernels are generated from the spec (dims baked as literals) into a cached module file.
"""

__all__ = [
    "supports",
    "fits",
    "forward_infer",
    "forward_train",
    "backward",
    "is_available",
]

import hashlib
import importlib.util
import os
from pathlib import Path

import torch

from ..._core.kernel_triton import _ACT_TL, _pow2, is_available
from .core import rollout_unsupported
from .r2dn import R2DNSpec, split_params

_KERNELS: dict[R2DNSpec, object] = {}

#: On-chip caps. The per-vector padded widths bound the register tiles individually; the
#: total tile area bounds them together, since the network's layers dominate at any useful
#: width and all of them stay resident across the whole rollout.
MAX_PX = 64
MAX_PV = 128
MAX_PU = 64
MAX_PY = 64
MAX_PM = 128
MAX_AREA = 32768


def _pads(spec: R2DNSpec) -> tuple[int, int, int, int]:
    return _pow2(spec.n_state), _pow2(spec.n_nl), _pow2(spec.n_input), _pow2(spec.n_output)


def _layer_pads(spec: R2DNSpec) -> list[tuple[int, int]]:
    """``(padded input width, padded output width)`` of every layer, output layer last."""
    pv = _pow2(spec.n_nl)
    widths = [pv, *(_pow2(m) for m in spec.hidden)]
    return [*zip(widths[:-1], widths[1:]), (widths[-1], pv)]


def _area(spec: R2DNSpec) -> int:
    """Total on-chip tile area: what has to stay in registers for the whole rollout."""
    px, pv, pu, py = _pads(spec)
    linear = px * px + pv * px + pu * px + px * pv + px * py + pu * pv + pv * py + pu * py
    return linear + sum(pi * po for pi, po in _layer_pads(spec))


def fits(spec: R2DNSpec) -> bool:
    """Whether the persistent kernels apply: every padded tile must stay on-chip."""
    px, pv, pu, py = _pads(spec)
    return (
        spec.act in _ACT_TL
        and px <= MAX_PX
        and pv <= MAX_PV
        and pu <= MAX_PU
        and py <= MAX_PY
        and all(_pow2(m) <= MAX_PM for m in spec.hidden)
        and _area(spec) <= MAX_AREA
    )


def _gen_source(spec: R2DNSpec) -> str:
    """Emit the spec-specialized Triton kernel module (inference fwd, training fwd, bwd)."""
    nx, nv, nu, ny = spec.n_state, spec.n_nl, spec.n_input, spec.n_output
    px, pv, pu, py = _pads(spec)
    pads = _layer_pads(spec)
    depth = len(spec.hidden)
    act, dact = _ACT_TL[spec.act]
    sizes = {"x": px, "v": pv, "u": pu, "y": py, **{f"m{i}": p for i, (_, p) in enumerate(pads)}}
    lines = [
        '"""Auto-generated by tsfast.models.architectures.ren.r2dn_backend_triton — do not edit."""',
        "import triton",
        "import triton.language as tl",
        "",
    ]

    def ranges(names) -> list[str]:
        return [f"    r{n} = tl.arange(0, {sizes[n]})" for n in names]

    def tile(name: str, rows: int, cols: int, rr: str, rc: str) -> str:
        return f"    {name} = tl.load({name}_ptr + r{rr}[:, None] * {cols} + r{rc}[None, :])"

    # the input range of layer l: the interconnection for the first, the previous width after
    def in_range(i: int) -> str:
        return "v" if i == 0 else f"m{i - 1}"

    net_args = ", ".join(f"w{i}t_ptr, lb{i}_ptr" for i in range(depth + 1))
    all_ranges = ["x", "v", "u", "y", *(f"m{i}" for i in range(depth + 1))]

    # ------------------------------------------------------------------- forward
    fwd_args = (
        "u_ptr, x0_ptr, at_ptr, b1t_ptr, b2t_ptr, c1t_ptr, c2t_ptr, d12t_ptr, d21t_ptr, d22t_ptr, "
        f"bx_ptr, bv_ptr, by_ptr, {net_args}, y_ptr, xlast_ptr"
    )

    def fwd_kernel(name: str, store: bool) -> list[str]:
        extra = ", xs_ptr, vs_ptr, ws_ptr" + "".join(f", a{i}_ptr" for i in range(depth)) if store else ""
        out = [
            "@triton.jit",
            f"def {name}({fwd_args}{extra}, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
            *ranges(all_ranges),
            tile("at", px, px, "x", "x"),
            tile("b1t", pv, px, "v", "x"),
            tile("b2t", pu, px, "u", "x"),
            tile("c1t", px, pv, "x", "v"),
            tile("c2t", px, py, "x", "y"),
            tile("d12t", pu, pv, "u", "v"),
            tile("d21t", pv, py, "v", "y"),
            tile("d22t", pu, py, "u", "y"),
            "    bx = tl.load(bx_ptr + rx)",
            "    bv = tl.load(bv_ptr + rv)",
            "    by = tl.load(by_ptr + ry)",
        ]
        for i, (pi, po) in enumerate(pads):
            out.append(tile(f"w{i}t", pi, po, in_range(i), f"m{i}"))
            out.append(f"    lb{i} = tl.load(lb{i}_ptr + rm{i})")
        out += [
            f"    x = tl.load(x0_ptr + pid * {nx} + rx, mask=rx < {nx}, other=0.0)",
            "    for t in tl.range(0, L, num_stages=NUM_STAGES):",
            "        base = pid * L + t",
            f"        ut = tl.load(u_ptr + base * {nu} + ru, mask=ru < {nu}, other=0.0)",
            "        v = bv + tl.sum(x[:, None] * c1t, axis=0) + tl.sum(ut[:, None] * d12t, axis=0)",
        ]
        for i in range(depth):
            src = "v" if i == 0 else f"a{i - 1}"
            out.append(f"        p{i} = lb{i} + tl.sum({src}[:, None] * w{i}t, axis=0)")
            out.append(f"        a{i} = " + act.format(a=f"p{i}"))
        out += [
            f"        w = lb{depth} + tl.sum({'v' if depth == 0 else f'a{depth - 1}'}[:, None] * w{depth}t, axis=0)",
            "        yv = by + tl.sum(x[:, None] * c2t, axis=0) + tl.sum(w[:, None] * d21t, axis=0)"
            " + tl.sum(ut[:, None] * d22t, axis=0)",
            f"        tl.store(y_ptr + base * {ny} + ry, yv, mask=ry < {ny})",
        ]
        if store:
            out += [
                f"        tl.store(xs_ptr + base * {nx} + rx, x, mask=rx < {nx})",
                f"        tl.store(vs_ptr + base * {nv} + rv, v, mask=rv < {nv})",
                f"        tl.store(ws_ptr + base * {nv} + rv, w, mask=rv < {nv})",
            ]
            out += [
                f"        tl.store(a{i}_ptr + base * {spec.hidden[i]} + rm{i}, a{i}, mask=rm{i} < {spec.hidden[i]})"
                for i in range(depth)
            ]
        out += [
            "        x = bx + tl.sum(x[:, None] * at, axis=0) + tl.sum(w[:, None] * b1t, axis=0)"
            " + tl.sum(ut[:, None] * b2t, axis=0)",
            f"    tl.store(xlast_ptr + pid * {nx} + rx, x, mask=rx < {nx})",
            "",
        ]
        return out

    lines += fwd_kernel("r2dn_fwd", store=False)
    lines += fwd_kernel("r2dn_fwd_train", store=True)

    # ------------------------------------------------------------------ backward
    bwd_net = ", ".join(f"w{i}_ptr" for i in range(depth + 1))
    lines += [
        "@triton.jit",
        "def r2dn_bwd(gy_ptr, gxl_ptr, " + "".join(f"a{i}_ptr, " for i in range(depth)) + "a_ptr, b1_ptr, c1_ptr, "
        f"c2_ptr, d21_ptr, {bwd_net}, lam_ptr, gv_ptr, " + "".join(f"gp{i}_ptr, " for i in range(depth)) + "gx0_ptr, "
        "L, NUM_STAGES: tl.constexpr):",
        "    pid = tl.program_id(0)",
        *ranges(all_ranges),
        tile("a", px, px, "x", "x"),
        tile("b1", px, pv, "x", "v"),
        tile("c1", pv, px, "v", "x"),
        tile("c2", py, px, "y", "x"),
        tile("d21", py, pv, "y", "v"),
    ]
    # untransposed: the adjoint sums run over each map's output index
    lines += [tile(f"w{i}", po, pi, f"m{i}", in_range(i)) for i, (pi, po) in enumerate(pads)]
    lines += [
        f"    carry = tl.load(gxl_ptr + pid * {nx} + rx, mask=rx < {nx}, other=0.0)",
        "    for t in tl.range(L - 1, -1, -1, num_stages=NUM_STAGES):",
        "        base = pid * L + t",
        f"        gyt = tl.load(gy_ptr + base * {ny} + ry, mask=ry < {ny}, other=0.0)",
        "        gw = tl.sum(gyt[:, None] * d21, axis=0) + tl.sum(carry[:, None] * b1, axis=0)",
        f"        g = tl.sum(gw[:, None] * w{depth}, axis=0)",
    ]
    for i in range(depth - 1, -1, -1):
        m = spec.hidden[i]
        lines += [
            f"        a{i} = tl.load(a{i}_ptr + base * {m} + rm{i}, mask=rm{i} < {m}, other=0.0)",
            f"        gp{i} = " + dact.format(z=f"a{i}") + " * g",
            f"        tl.store(gp{i}_ptr + base * {m} + rm{i}, gp{i}, mask=rm{i} < {m})",
            f"        g = tl.sum(gp{i}[:, None] * w{i}, axis=0)",
        ]
    lines += [
        f"        tl.store(lam_ptr + base * {nx} + rx, carry, mask=rx < {nx})",
        f"        tl.store(gv_ptr + base * {nv} + rv, g, mask=rv < {nv})",
        "        carry = tl.sum(carry[:, None] * a, axis=0) + tl.sum(gyt[:, None] * c2, axis=0)"
        " + tl.sum(g[:, None] * c1, axis=0)",
        f"    tl.store(gx0_ptr + pid * {nx} + rx, carry, mask=rx < {nx})",
        "",
    ]
    return "\n".join(lines)


def _get_kernels(spec: R2DNSpec):
    """Generate, cache on disk, and import the kernel module for this spec."""
    mod = _KERNELS.get(spec)
    if mod is None:
        src = _gen_source(spec)
        tag = hashlib.md5(src.encode(), usedforsecurity=False).hexdigest()[:10]
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser() / "tsfast" / "r2dn_triton"
        cache_dir.mkdir(parents=True, exist_ok=True)
        path = cache_dir / f"r2dn_{tag}.py"
        if not path.exists() or path.read_text() != src:
            path.write_text(src)
        loader = importlib.util.spec_from_file_location(f"tsfast_r2dn_triton_{tag}", path)
        mod = importlib.util.module_from_spec(loader)
        loader.loader.exec_module(mod)
        _KERNELS[spec] = mod
    return mod


def _num_warps(spec: R2DNSpec) -> int:
    return 2 if max(_pads(spec)) <= 64 and _area(spec) <= 8192 else 8


@torch.no_grad()
def _pad(t: torch.Tensor, rows: int, cols: int, transpose: bool) -> torch.Tensor:
    src = t.t() if transpose else t
    out = torch.zeros(rows, cols, device=t.device, dtype=torch.float32)
    out[: src.shape[0], : src.shape[1]] = src
    return out


@torch.no_grad()
def _pad_vec(t: torch.Tensor, n: int) -> torch.Tensor:
    out = torch.zeros(n, device=t.device, dtype=torch.float32)
    out[: t.shape[0]] = t
    return out


@torch.no_grad()
def _fwd_bufs(spec: R2DNSpec, params: list[torch.Tensor]) -> list[torch.Tensor]:
    """Transposed, zero-padded tiles in the forward kernel's argument order."""
    px, pv, pu, py = _pads(spec)
    lin, layers = split_params([p.detach() for p in params])
    a, b1, b2, c1, c2, d12, d21, d22, bx, bv, by = lin
    bufs = [
        _pad(a, px, px, True),
        _pad(b1, pv, px, True),
        _pad(b2, pu, px, True),
        _pad(c1, px, pv, True),
        _pad(c2, px, py, True),
        _pad(d12, pu, pv, True),
        _pad(d21, pv, py, True),
        _pad(d22, pu, py, True),
        _pad_vec(bx, px),
        _pad_vec(bv, pv),
        _pad_vec(by, py),
    ]
    for (pi, po), (w, c) in zip(_layer_pads(spec), layers):
        bufs += [_pad(w, pi, po, True), _pad_vec(c, po)]
    return bufs


@torch.no_grad()
def _bwd_bufs(spec: R2DNSpec, params: list[torch.Tensor]) -> list[torch.Tensor]:
    """Untransposed, zero-padded tiles in the backward kernel's argument order.

    The adjoint sums run over the *output* index of each map, so the backward reads the
    matrices the way they are stored.
    """
    px, pv, pu, py = _pads(spec)
    lin, layers = split_params([p.detach() for p in params])
    bufs = [
        _pad(lin[0], px, px, False),  # A
        _pad(lin[1], px, pv, False),  # B1
        _pad(lin[3], pv, px, False),  # C1
        _pad(lin[4], py, px, False),  # C2
        _pad(lin[6], py, pv, False),  # D21
    ]
    return bufs + [_pad(w, po, pi, False) for (pi, po), (w, _) in zip(_layer_pads(spec), layers)]


def supports(spec: R2DNSpec, u: torch.Tensor, x0: torch.Tensor) -> str | None:
    """Reason the persistent Triton kernels cannot handle these inputs, or None when they can."""
    reason = rollout_unsupported(spec, u, x0, "cuda", (torch.float32,))
    if reason is not None:
        return reason
    if not is_available():
        return "no CUDA / triton"
    if not fits(spec):
        return (
            f"spec exceeds the on-chip caps (padded n_state<={MAX_PX}, n_nl<={MAX_PV}, "
            f"n_input<={MAX_PU}, n_output<={MAX_PY}, hidden<={MAX_PM}, total tile area<={MAX_AREA})"
        )
    return None


def _run_fwd(spec: R2DNSpec, u, x0, params, store: bool):
    mod = _get_kernels(spec)
    b, ln = u.shape[0], u.shape[1]
    dev = u.device
    y = torch.empty(b, ln, spec.n_output, device=dev, dtype=torch.float32)
    xlast = torch.empty(b, spec.n_state, device=dev, dtype=torch.float32)
    bufs = _fwd_bufs(spec, params)
    warps = _num_warps(spec)
    if store:
        xs = torch.empty(b, ln, spec.n_state, device=dev, dtype=torch.float32)
        vs = torch.empty(b, ln, spec.n_nl, device=dev, dtype=torch.float32)
        ws = torch.empty(b, ln, spec.n_nl, device=dev, dtype=torch.float32)
        acts = [torch.empty(b, ln, m, device=dev, dtype=torch.float32) for m in spec.hidden]
        mod.r2dn_fwd_train[(b,)](u, x0, *bufs, y, xlast, xs, vs, ws, *acts, ln, NUM_STAGES=2, num_warps=warps)
        return y, xlast, xs, vs, ws, acts
    mod.r2dn_fwd[(b,)](u, x0, *bufs, y, xlast, ln, NUM_STAGES=2, num_warps=warps)
    return y, xlast, None, None, None, None


def forward_infer(spec: R2DNSpec, u, x0, params) -> tuple[torch.Tensor, torch.Tensor]:
    """Rollout without stored intermediates: returns ``(y, x_L)``."""
    y, xlast, *_ = _run_fwd(spec, u, x0, params, store=False)
    return y, xlast


def forward_train(spec: R2DNSpec, u, x0, params) -> tuple:
    """Rollout that also stores the BPTT tape: returns ``(y, x_L, xs, vs, ws, acts)``."""
    return _run_fwd(spec, u, x0, params, store=True)


def backward(spec: R2DNSpec, gy, gxl, acts, params) -> tuple:
    """Sequential adjoint recurrence: returns ``(lam, gv, gps, gx0)`` for the shared GEMM stage."""
    mod = _get_kernels(spec)
    b, ln = gy.shape[0], gy.shape[1]
    dev = gy.device
    lam = torch.empty(b, ln, spec.n_state, device=dev, dtype=torch.float32)
    gv = torch.empty(b, ln, spec.n_nl, device=dev, dtype=torch.float32)
    gps = [torch.empty(b, ln, m, device=dev, dtype=torch.float32) for m in spec.hidden]
    gx0 = torch.empty(b, spec.n_state, device=dev, dtype=torch.float32)
    mod.r2dn_bwd[(b,)](
        gy, gxl, *acts, *_bwd_bufs(spec, params), lam, gv, *gps, gx0, ln, NUM_STAGES=2, num_warps=_num_warps(spec)
    )
    return lam, gv, gps, gx0
