"""Generated-Triton execution backend for NarxMLP: persistent GPU free-run rollout and BPTT.

The recurrence runs as ONE persistent kernel: all L steps in a single launch, weights resident
on-chip, one program per trajectory. Each layer is a broadcast-reduce GEMV (plain FMA, no
tensor-core tile minimum), so single-trajectory programs fill the GPU at small batch. The
lag buffer lives in registers as one flattened tile; the shift-append after every step is a
constant 0/1 matrix contraction built once from ``tl.arange`` (registers cannot be indexed
dynamically, and the matrix form keeps the generated code independent of ``na``).

The kernel owns only the sequential feedback recurrence: it receives the precomputed
input-window contribution ``hu = conv_u(u)`` per step and returns the prediction sequence.
Backward follows the split-BPTT design: a persistent reverse-sweep kernel carries the
lag-buffer adjoint and emits the per-step adjoints; parameter gradients are batched cuBLAS
GEMMs over the ``[B*L, .]`` flattened adjoints (``narx_param_grads``), and the gradient
w.r.t. ``hu`` hands the chain back to autograd for the convolution path.

Kernels are generated from the layer spec (dims baked as literals) into a cached module file;
all padded widths, including the flattened buffer, must stay <= 128.
"""

__all__ = [
    "triton_rollout",
    "is_available",
    "fits",
]

import hashlib
import importlib.util
import os
from pathlib import Path

import torch

from ..._core.kernel_triton import _ACT_TL, _MAX_PADDED_WIDTH, _pow2, is_available
from .core import NarxSpec, check_rollout_args, narx_param_grads

_KERNELS: dict[NarxSpec, object] = {}


def fits(spec: NarxSpec) -> bool:
    """Whether the persistent GEMV kernels apply: all padded widths must stay on-chip."""
    return spec.act in _ACT_TL and max(_pow2(d) for d in spec.dims) <= _MAX_PADDED_WIDTH


def _gen_source(spec: NarxSpec) -> str:
    """Emit the spec-specialized Triton kernel module (inference fwd, training fwd, bwd)."""
    ny, nb, k = spec.n_y, spec.n_buf, spec.n_linear
    py, pb = _pow2(ny), _pow2(nb)
    ph = [_pow2(h) for h in spec.hidden]
    pdims = (pb, *ph, py)
    act, dact = _ACT_TL[spec.act]

    ranges = sorted({py, pb, *ph})
    lines = [
        '"""Auto-generated by tsfast.models.architectures.narx.backend_triton — do not edit."""',
        "import triton",
        "import triton.language as tl",
        "",
    ]

    def emit_ranges(out: list[str]):
        for n in ranges:
            out.append(f"    r{n} = tl.arange(0, {n})")

    def emit_shift_matrices(out: list[str]):
        # shift: v'[j] = v[j + NY]; place: v'[NB - NY + c] = fed[c]. Built as 0/1
        # float matrices so the register buffer updates as two tiny contractions.
        out.append(f"    shift = (r{pb}[:, None] == (r{pb}[None, :] + {ny})).to(tl.float32)")
        out.append(f"    place = (r{pb}[None, :] == (r{py}[:, None] + {nb - ny})).to(tl.float32)")

    def emit_weight_loads(out: list[str], with_biases: bool):
        out.append(f"    wy = tl.load(wy_ptr + r{pb}[:, None] * {pdims[1]} + r{pdims[1]}[None, :])")
        for i in range(1, k):
            out.append(
                f"    w{i} = tl.load(w{i}_ptr + r{pdims[i]}[:, None] * {pdims[i + 1]} + r{pdims[i + 1]}[None, :])"
            )
            if with_biases:
                out.append(f"    c{i} = tl.load(c{i}_ptr + r{pdims[i + 1]})")

    h0, p0 = spec.hidden[0], ph[0]
    humask = f", mask=(r{p0}[None, :] < {h0}), other=0.0" if p0 != h0 else ""
    ymask = f", mask=(r{py}[None, :] < {ny}), other=0.0" if py != ny else ""
    ysmask = f", mask=(r{py}[None, :] < {ny})" if py != ny else ""

    def fwd_kernel(name: str, store_z: bool) -> list[str]:
        w_args = "wy_ptr" + "".join(f", w{i}_ptr, c{i}_ptr" for i in range(1, k))
        z_args = "".join(f"z{i}_ptr, " for i in range(k - 1)) if store_z else ""
        out = [
            "@triton.jit",
            f"def {name}(hu_ptr, ytrue_ptr, {w_args}, out_ptr, {z_args}washout, B, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
        ]
        emit_ranges(out)
        emit_shift_matrices(out)
        emit_weight_loads(out, with_biases=True)
        out.append(f"    v = tl.zeros([1, {pb}], dtype=tl.float32)")
        out.append("    for t in tl.range(0, L, num_stages=NUM_STAGES):")
        out.append(f"        hu = tl.load(hu_ptr + pid * (L * {h0}) + t * {h0} + r{p0}[None, :]{humask})")
        prev = None
        for i in range(k):
            dst = "y" if i == k - 1 else f"z{i}"
            if i == 0:
                expr = "tl.sum(v[:, :, None] * wy[None, :, :], axis=1) + hu"
            else:
                expr = f"tl.sum({prev}[:, :, None] * w{i}[None, :, :], axis=1) + c{i}[None, :]"
            if i < k - 1:
                out.append(f"        {dst} = " + act.format(a=expr))
                if store_z:
                    h, p = spec.hidden[i], ph[i]
                    zmask = f", mask=(r{p}[None, :] < {h})" if p != h else ""
                    out.append(f"        tl.store(z{i}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :], {dst}{zmask})")
            else:
                out.append(f"        {dst} = {expr}")
            prev = dst
        out += [
            f"        tl.store(out_ptr + pid * (L * {ny}) + t * {ny} + r{py}[None, :], y{ysmask})",
            f"        yt = tl.load(ytrue_ptr + pid * (L * {ny}) + t * {ny} + r{py}[None, :]{ymask})",
            "        fed = tl.where(t < washout, yt, y)",
            "        v = tl.sum(v[:, :, None] * shift[None, :, :], axis=1)"
            " + tl.sum(fed[:, :, None] * place[None, :, :], axis=1)",
            "",
        ]
        return out

    def bwd_kernel() -> list[str]:
        z_args = "".join(f"z{i}_ptr, " for i in range(k - 1))
        w_args = "wy_ptr" + "".join(f", w{i}_ptr" for i in range(1, k))
        ga_args = "".join(f"ga{i}_ptr, " for i in range(k - 1))
        out = [
            "@triton.jit",
            f"def narx_bwd(gout_ptr, {z_args}{w_args}, gy_ptr, gfed_ptr, {ga_args}"
            "washout, B, L, NUM_STAGES: tl.constexpr):",
            "    pid = tl.program_id(0)",
        ]
        emit_ranges(out)
        emit_shift_matrices(out)
        emit_weight_loads(out, with_biases=False)
        out.append(f"    carry = tl.zeros([1, {pb}], dtype=tl.float32)")
        out.append("    for ti in tl.range(0, L, num_stages=NUM_STAGES):")
        out.append("        t = L - 1 - ti")
        out += [
            "        gfed = tl.sum(carry[:, :, None] * tl.trans(place)[None, :, :], axis=1)",
            f"        tl.store(gfed_ptr + pid * (L * {ny}) + t * {ny} + r{py}[None, :], gfed{ysmask})",
            f"        gout = tl.load(gout_ptr + pid * (L * {ny}) + t * {ny} + r{py}[None, :]{ymask})",
            "        gy = gout + tl.where(t >= washout, gfed, 0.0)",
            f"        tl.store(gy_ptr + pid * (L * {ny}) + t * {ny} + r{py}[None, :], gy{ysmask})",
        ]
        prev = "gy"
        for i in range(k - 1, 0, -1):
            h, p = spec.hidden[i - 1], ph[i - 1]
            zmask = f", mask=(r{p}[None, :] < {h}), other=0.0" if p != h else ""
            zsmask = f", mask=(r{p}[None, :] < {h})" if p != h else ""
            out.append(f"        zv{i - 1} = tl.load(z{i - 1}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :]{zmask})")
            out.append(f"        gh{i - 1} = tl.sum({prev}[:, None, :] * w{i}[None, :, :], axis=2)")
            out.append(f"        ga{i - 1} = gh{i - 1} * " + dact.format(z=f"zv{i - 1}"))
            out.append(
                f"        tl.store(ga{i - 1}_ptr + pid * (L * {h}) + t * {h} + r{p}[None, :], ga{i - 1}{zsmask})"
            )
            prev = f"ga{i - 1}"
        out += [
            f"        carry = tl.sum({prev}[:, None, :] * wy[None, :, :], axis=2)"
            " + tl.sum(carry[:, :, None] * tl.trans(shift)[None, :, :], axis=1)",
            "",
        ]
        return out

    lines += fwd_kernel("narx_fwd", store_z=False)
    lines += fwd_kernel("narx_fwd_train", store_z=True)
    lines += bwd_kernel()
    return "\n".join(lines)


def _get_kernels(spec: NarxSpec):
    """Generate, cache on disk, and import the kernel module for this spec."""
    mod = _KERNELS.get(spec)
    if mod is None:
        src = _gen_source(spec)
        tag = hashlib.md5(src.encode()).hexdigest()[:10]
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser() / "tsfast" / "narx_triton"
        cache_dir.mkdir(parents=True, exist_ok=True)
        path = cache_dir / f"narx_{tag}.py"
        if not path.exists() or path.read_text() != src:
            path.write_text(src)
        spec_ = importlib.util.spec_from_file_location(f"tsfast_narx_triton_{tag}", path)
        mod = importlib.util.module_from_spec(spec_)
        spec_.loader.exec_module(mod)
        _KERNELS[spec] = mod
    return mod


def _num_warps(spec: NarxSpec) -> int:
    # findings from the SSM GEMV kernels: nw=2 up to width 64, nw=8 at 128 (nw=4 spills)
    return 2 if max(_pow2(d) for d in spec.dims) <= 64 else 8


@torch.no_grad()
def _prep_weights(spec: NarxSpec, weights: list[torch.Tensor], biases: list[torch.Tensor] | None) -> list[torch.Tensor]:
    """Pad/transpose the raw parameters into the kernel layout.

    Returns ``[wy, w1, c1, ...]`` (biases interleaved) when biases are given — the
    forward-kernel argument order — or just the weight buffers for the backward kernel.
    The feedback weight has no bias; its bias lives in the precomputed ``hu``.
    """
    k = spec.n_linear
    pb = _pow2(spec.n_buf)
    ph = [_pow2(h) for h in spec.hidden]
    pdims = (pb, *ph, _pow2(spec.n_y))
    dev = weights[0].device
    wy = weights[0]
    wyp = torch.zeros(pb, pdims[1], device=dev)
    wyp[: spec.n_buf, : wy.shape[0]] = wy.t()
    bufs = [wyp]
    for i in range(1, k):
        w = weights[i]
        wp = torch.zeros(pdims[i], pdims[i + 1], device=dev)
        wp[: w.shape[1], : w.shape[0]] = w.t()
        bufs.append(wp)
        if biases is not None:
            cp = torch.zeros(pdims[i + 1], device=dev)
            cp[: biases[i - 1].shape[0]] = biases[i - 1]
            bufs.append(cp)
    return [b.contiguous() for b in bufs]


def _run_fwd(mod, spec: NarxSpec, hu, y_true, washout, params, store_z, num_warps):
    B, L = hu.shape[0], hu.shape[1]
    dev = hu.device
    out = torch.empty(B, L, spec.n_y, device=dev, dtype=torch.float32)
    bufs = _prep_weights(spec, [w.detach() for w in [params[0], *params[1::2]]], [c.detach() for c in params[2::2]])
    if store_z:
        zs = [torch.empty(B, L, h, device=dev, dtype=torch.float32) for h in spec.hidden]
        mod.narx_fwd_train[(B,)](hu, y_true, *bufs, out, *zs, washout, B, L, NUM_STAGES=3, num_warps=num_warps)
    else:
        zs = []
        mod.narx_fwd[(B,)](hu, y_true, *bufs, out, washout, B, L, NUM_STAGES=3, num_warps=num_warps)
    return out, zs


class _TritonNarxRollout(torch.autograd.Function):
    @staticmethod
    def forward(ctx, mod, spec, washout, hu, y_true, *params):
        hu = hu.contiguous()
        y_true = y_true.contiguous()
        nw = _num_warps(spec)
        out, zs = _run_fwd(mod, spec, hu, y_true, washout, params, store_z=True, num_warps=nw)
        ctx.mod, ctx.spec, ctx.washout, ctx.nw = mod, spec, washout, nw
        ctx.save_for_backward(y_true, out, *zs, *params[0:1], *params[1::2])
        return out

    @staticmethod
    def backward(ctx, grad_out):
        mod, spec, washout = ctx.mod, ctx.spec, ctx.washout
        k = spec.n_linear
        saved = ctx.saved_tensors
        y_true, out = saved[0], saved[1]
        zs = list(saved[2 : 2 + k - 1])
        weights = list(saved[2 + k - 1 :])  # [wy, w1, ..., w_{k-1}]
        B, L = out.shape[0], out.shape[1]
        dev = out.device
        bufs = _prep_weights(spec, [w.detach() for w in weights], biases=None)
        gy = torch.empty(B, L, spec.n_y, device=dev, dtype=torch.float32)
        gfed = torch.empty(B, L, spec.n_y, device=dev, dtype=torch.float32)
        gas = [torch.empty_like(z) for z in zs]
        mod.narx_bwd[(B,)](
            grad_out.contiguous(), *zs, *bufs, gy, gfed, *gas, washout, B, L, NUM_STAGES=3, num_warps=ctx.nw
        )
        grads = narx_param_grads(spec, y_true, out, washout, zs, gy, gas)
        dhu = gas[0] if ctx.needs_input_grad[3] else None
        dy_true = None
        if ctx.needs_input_grad[4]:
            t = torch.arange(L, device=dev)
            dy_true = gfed * (t < washout)[None, :, None]
        return (None, None, None, dhu, dy_true, *grads)


def triton_rollout(
    spec: NarxSpec, hu: torch.Tensor, y_true: torch.Tensor, washout: int, params: list[torch.Tensor]
) -> torch.Tensor:
    """Run the free-run recurrence through the generated persistent Triton kernels (autograd-capable)."""
    check_rollout_args(spec, hu, y_true, "cuda")
    if not fits(spec):
        raise RuntimeError(
            f"spec {spec} exceeds the triton backend envelope (padded widths <= {_MAX_PADDED_WIDTH}); "
            "use backend='compiled'"
        )
    mod = _get_kernels(spec)
    if not torch.is_grad_enabled() or not any(t.requires_grad for t in [hu, y_true, *params]):
        out, _ = _run_fwd(
            mod, spec, hu.contiguous(), y_true.contiguous(), washout, params, store_z=False, num_warps=_num_warps(spec)
        )
        return out
    return _TritonNarxRollout.apply(mod, spec, washout, hu, y_true, *params)
