#AUTOGENERATED! DO NOT EDIT! File to edit: dev/03_tbptt_dl.ipynb (unless otherwise specified).

__all__ = []

#Cell
from .core import *
from .model import *
from .learner import *
from fastai2.basics import *

import math