"""Persistent-Triton backend for banks of scalar all-pole (order-na IIR) recurrences.

Computes ``y_t = w_t - sum_{i=1..na} a_i * y_{t-i}`` per lane — the dynoNet G-block
denominator. The companion-matrix state of ``LinearDynamicalOperator`` is a pure shift
register of past outputs (``x_t[j] = y_{t-j}``), so the whole matrix recurrence collapses
to this scalar filter: one input load and one output store per lane-step, versus the
``na``-wide state tensor the matrix doubling scan re-reads ``ceil(log2(L))`` times.

Each program owns a block of lanes and streams time sequentially, carrying the ``na``
most recent outputs in registers. Registers cannot be indexed dynamically and a 0/1
shift-matrix contraction costs ~na^2 tile ops per step (measured ~10x over the whole
kernel's roofline), so — like the SSM/NARX rollout kernels — the kernels are
code-generated per ``na`` with the delay line as explicit variables ``s0..s{na-1}``;
the shift is then pure SSA renaming and a step costs ~na FMAs. Generated modules are
cached on disk and autotuned per shape. A pole-diagonalization onto the complex
diagonal kernel is not an option here: ``a = 0`` (dynoNet's initialization) makes the
companion matrix nilpotent, with no eigenbasis.

The adjoint of an all-pole filter is the same all-pole filter run backwards:
``G_t = g_t - sum_i a_i * G_{t+i}`` with zero final state and ``grad_w = G``. The
backward kernel walks time descending, carries the ``G`` delay line in registers, and
accumulates ``grad_a_i = -sum_u G_{u+i} * y_u`` on the fly: at step ``u`` the delay line
already holds exactly ``G_{u+1..u+na}``, so the accumulation reuses it with no extra
state. The initial-state tap corrections of ``grad_a`` and all of ``grad_y0`` touch only
the first ``na`` adjoint values and are finished on the torch side, as are the broadcast
reductions. Only the coefficients and the forward output are saved, so backward memory
is O(L). Real float32 only.

The initial state ``y0`` holds the outputs preceding the sequence, newest first
(``y0[..., j] = y_{-1-j}``) — exactly the carried IIR state of the dynoNet operator.
"""

__all__ = [
    "supports",
    "run",
]

import hashlib
import importlib.util
import os
from pathlib import Path

import torch
import torch.nn.functional as F
from torch.autograd.function import once_differentiable

try:
    import triton

    _HAVE_TRITON = True
except ImportError:  # pragma: no cover - environment without triton
    _HAVE_TRITON = False

_MAX_NA = 16  # delay line, coefficients, and grad accumulators live in registers per lane
_KERNELS: dict[int, object] = {}


def _gen_source(na: int) -> str:
    """Emit the na-specialized kernel module (forward + backward) with an unrolled delay line."""
    taps = range(na)
    dot = " + ".join(f"a{k} * s{k}" for k in taps)
    shift = "".join(f"        s{k} = s{k - 1}\n" for k in reversed(range(1, na)))
    lines = [
        '"""Auto-generated by tsfast.models.architectures.dynonet.allpole_triton — do not edit."""',
        "import triton",
        "import triton.language as tl",
        "",
        "",
        "def _configs():",
        "    # BLOCK (lanes/program) trades load width against grid size — dynoNet lane counts",
        "    # (B * n_pairs, ~500-5000) need small blocks to oversubscribe the SMs; num_stages",
        "    # lets the pipeliner prefetch the per-step loads past the register recurrence.",
        '    return [triton.Config({"BLOCK": bl}, num_warps=w, num_stages=s)'
        " for bl in (8, 16, 32) for w in (1, 2) for s in (1, 3)]",
        "",
        "",
        '@triton.autotune(configs=_configs(), key=["LANES", "L", "HAS_Y0"])',
        "@triton.jit",
        "def allpole_fwd(a_ptr, w_ptr, y0_ptr, y_ptr, LANES, L, HAS_Y0: tl.constexpr, BLOCK: tl.constexpr):",
        "    pid = tl.program_id(0)",
        "    lane = pid * BLOCK + tl.arange(0, BLOCK)",
        "    lmask = lane < LANES",
    ]
    lines += [f"    a{k} = tl.load(a_ptr + lane * {na} + {k}, mask=lmask, other=0.0)" for k in taps]
    lines += ["    if HAS_Y0:"]
    lines += [f"        s{k} = tl.load(y0_ptr + lane * {na} + {k}, mask=lmask, other=0.0)" for k in taps]
    lines += ["    else:"]
    lines += [f"        s{k} = tl.zeros([BLOCK], dtype=tl.float32)" for k in taps]
    lines += [
        "    row = lane * L",
        "    for t in tl.range(0, L):",
        "        wt = tl.load(w_ptr + row + t, mask=lmask, other=0.0)",
        f"        yt = wt - ({dot})",
        "        tl.store(y_ptr + row + t, yt, mask=lmask)",
        shift + "        s0 = yt",
        "",
        "",
        '@triton.autotune(configs=_configs(), key=["LANES", "L"])',
        "@triton.jit",
        "def allpole_bwd(a_ptr, g_ptr, y_ptr, gw_ptr, ga_ptr, LANES, L, BLOCK: tl.constexpr):",
        "    pid = tl.program_id(0)",
        "    lane = pid * BLOCK + tl.arange(0, BLOCK)",
        "    lmask = lane < LANES",
    ]
    lines += [f"    a{k} = tl.load(a_ptr + lane * {na} + {k}, mask=lmask, other=0.0)" for k in taps]
    lines += [f"    s{k} = tl.zeros([BLOCK], dtype=tl.float32)" for k in taps]  # s_k = G_{t+1+k}
    lines += [f"    ga{k} = tl.zeros([BLOCK], dtype=tl.float32)" for k in taps]
    lines += [
        "    row = lane * L",
        "    for ti in tl.range(0, L):",
        "        t = L - 1 - ti",
        "        gt = tl.load(g_ptr + row + t, mask=lmask, other=0.0)",
        f"        G = gt - ({dot})",
        "        tl.store(gw_ptr + row + t, G, mask=lmask)",
        "        yu = tl.load(y_ptr + row + t, mask=lmask, other=0.0)",
        # grad_a_i = -sum_u G_{u+i} y_u: the pre-shift delay line holds G_{u+1+k} (host negates)
    ]
    lines += [f"        ga{k} += s{k} * yu" for k in taps]
    lines += [shift + "        s0 = G"]
    lines += [f"    tl.store(ga_ptr + lane * {na} + {k}, ga{k}, mask=lmask)" for k in taps]
    lines += [""]
    return "\n".join(lines)


def _get_kernels(na: int):
    """Generate, cache on disk, and import the kernel module for this filter order."""
    mod = _KERNELS.get(na)
    if mod is None:
        src = _gen_source(na)
        tag = hashlib.md5(src.encode()).hexdigest()[:10]
        cache_dir = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser() / "tsfast" / "allpole_triton"
        cache_dir.mkdir(parents=True, exist_ok=True)
        path = cache_dir / f"allpole_{tag}.py"
        if not path.exists() or path.read_text() != src:
            path.write_text(src)
        spec_ = importlib.util.spec_from_file_location(f"tsfast_allpole_triton_{tag}", path)
        mod = importlib.util.module_from_spec(spec_)
        spec_.loader.exec_module(mod)
        _KERNELS[na] = mod
    return mod


def supports(a: torch.Tensor, w: torch.Tensor, y0: torch.Tensor | None) -> str | None:
    """Reason this backend cannot handle the inputs, or None when it can (see module docstring)."""
    if not _HAVE_TRITON:
        return "triton not importable"
    if w.device.type != "cuda":
        return f"input on {w.device.type}, triton backend is CUDA-only"
    if any(t is not None and t.dtype != torch.float32 for t in (a, w, y0)):
        return "needs float32 tensors"
    if w.dim() < 2:
        return "w must have at least a batch and a time axis"
    na = a.shape[-1]
    if not 1 <= na <= _MAX_NA:
        return f"na={na} outside the supported register-resident range [1, {_MAX_NA}]"
    lead = w.shape[:-1]
    try:
        if torch.broadcast_shapes(a.shape[:-1], lead) != lead:
            return f"a leading dims {tuple(a.shape[:-1])} do not broadcast into {tuple(lead)}"
        if y0 is not None and torch.broadcast_shapes(y0.shape[:-1], lead) != lead:
            return f"y0 leading dims {tuple(y0.shape[:-1])} do not broadcast into {tuple(lead)}"
    except RuntimeError as e:
        return f"shape mismatch: {e}"
    if y0 is not None and y0.shape[-1] != na:
        return f"y0 state dim {y0.shape[-1]} != na {na}"
    return None


def _prep(a, w, y0):
    """Broadcast coefficients/state over w's leading dims and flatten to [lanes, ...]."""
    lead, L, na = w.shape[:-1], w.shape[-1], a.shape[-1]
    a_lane = a.broadcast_to(lead + (na,)).contiguous().reshape(-1, na)
    w_flat = w.contiguous().reshape(-1, L)
    y0_lane = y0.broadcast_to(lead + (na,)).contiguous().reshape(-1, na) if y0 is not None else None
    return a_lane, w_flat, y0_lane, (lead, L, na)


def _grid(lanes):
    return lambda meta: (triton.cdiv(lanes, meta["BLOCK"]),)


def _forward(a_lane, w_flat, y0_lane, meta):
    _lead, L, na = meta
    y = torch.empty_like(w_flat)
    lanes = w_flat.shape[0]
    y0_arg = y0_lane if y0_lane is not None else a_lane  # unused pointer when HAS_Y0 is False
    _get_kernels(na).allpole_fwd[_grid(lanes)](a_lane, w_flat, y0_arg, y, lanes, L, HAS_Y0=y0_lane is not None)
    return y


class _AllPoleTriton(torch.autograd.Function):
    @staticmethod
    def forward(ctx, a, w, y0):
        a_lane, w_flat, y0_lane, meta = _prep(a, w, y0)
        y = _forward(a_lane, w_flat, y0_lane, meta)
        ctx.meta = meta
        ctx.shapes = (a.shape, w.shape, None if y0 is None else y0.shape)
        ctx.save_for_backward(a_lane, y, y0_lane)
        return y.reshape(w.shape)

    @staticmethod
    @once_differentiable
    def backward(ctx, grad_out):
        lead, L, na = ctx.meta
        a_shape, w_shape, y0_shape = ctx.shapes
        a_lane, y, y0_lane = ctx.saved_tensors
        lanes = y.shape[0]
        g = grad_out.reshape(lanes, L).contiguous()
        gw = torch.empty_like(g)
        ga = torch.empty_like(a_lane)
        _get_kernels(na).allpole_bwd[_grid(lanes)](a_lane, g, y, gw, ga, lanes, L)
        grad_a = grad_w = grad_y0 = None
        m = min(na, L)  # both head computations below touch only the first na adjoint values
        if ctx.needs_input_grad[0]:
            if y0_lane is not None:
                # initial-state taps: grad_a_i also collects -sum_{k=1..i} G_{i-k} y0[k-1];
                # left-padding zeros the out-of-range taps, flip aligns the correlation
                win = F.pad(y0_lane, (m - 1, 0)).unfold(-1, m, 1)
                ga += (win.flip(-1) * gw[:, None, :m]).sum(-1)
            grad_a = (-ga).reshape(lead + (na,)).sum_to_size(a_shape)
        if ctx.needs_input_grad[1]:
            grad_w = gw.reshape(w_shape)
        if y0_lane is not None and ctx.needs_input_grad[2]:
            # grad_y0_j = -sum_{i=j+1..na} a_i G_{i-1-j}; right-padding zeros the taps beyond na
            win = F.pad(a_lane, (0, m - 1)).unfold(-1, m, 1)
            grad_y0 = -(win * gw[:, None, :m]).sum(-1).reshape(lead + (na,)).sum_to_size(y0_shape)
        return grad_a, grad_w, grad_y0


def run(a: torch.Tensor, w: torch.Tensor, y0: torch.Tensor | None) -> torch.Tensor:
    """Run the all-pole filter bank through the persistent Triton kernels (autograd-capable)."""
    if not torch.is_grad_enabled() or not any(t is not None and t.requires_grad for t in (a, w, y0)):
        a_lane, w_flat, y0_lane, meta = _prep(a, w, y0)
        return _forward(a_lane, w_flat, y0_lane, meta).reshape(w.shape)
    return _AllPoleTriton.apply(a, w, y0)
